### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by hlbrown** [hlbrown/just-in-time#4]
Work on the body section to include the 2 portal placeholders and the emergency map section +  the testimonials portion 

![image](https://user-images.githubusercontent.com/16610213/140628318-ffa99123-1d8c-489c-a1ce-805591af7489.png)

**Comment by DionneNoellaBarretto** [comment]
the map functionality needs to be revisited as the map isnt resizing well for small screens using mui grid / containers / box or card..
